#
# script based on https://github.com/thisni1s/telescope/
#

FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set the entry point
CMD ["python3"]
