from enum import Enum


class LogNamesEnum (Enum):
    analyzer = 'analyzer.log'
    conn = 'conn.log'
    dhcp = 'dhcp.log'
    dns = 'dns.log'
    dpd = 'dpd.log'
    files = 'files.log'
    http = 'http.log'
    kerberos = 'kerberos.log'
    ldap_search = 'ldap_search.log'
    loaded_scripts = 'loaded_scripts.log'
    notice = 'notice.log'
    ntp = 'ntp.log'
    ocsp = 'ocsp.log'
    packet_filter = 'packet_filter.log'
    quic = 'quic.log'
    radius = 'radius.log'
    sip = 'sip.log'
    snmp = 'snmp.log'
    ssh = 'ssh.log'
    ssl = 'ssl.log'
    syslog = 'syslog.log'
    tunnel = 'tunnel.log'
    unknown_protocols = 'unknown_protocols.log'
    weird = 'weird.log'
    x509 = 'x509.log'
    notWsDiscovery = 'notWsDiscovery.log'
    portscans = 'portscans.log'
    addressscans = 'addressscans.log'
    connudp = 'connudp'
    scanner = 'scanner'
    xcaddressnotice = 'caddressnotice.log'
    yaddressconn = 'caddressconn.log'
    zportnotice = 'cportnotice.log'
    vportconn = 'cportconn.log'
    mbackscatterconn = 'cbackscatterconn.log'

